### ISSUE TITLE
Comments in archived HTML file don't match those on Reddit

### ISSUE THREAD

**Issue by fturco** [libertysoft3/reddit-html-archiver#10]
I issued the following commands:

    ./fetch_links.py Frugal 2019-08-01 2019-09-11
    ./write_html.py

Then I compared the following pages:

* file:///path/to/reddit-html-archiver/r/frugal/comments/c/y/h/y/j/d/what_are_some_freecheap_activities_you_do_for_fun.html
* https://www.reddit.com/r/Frugal/comments/cyhyjd/what_are_some_freecheap_activities_you_do_for_fun/

On Reddit there's [this comment](https://www.reddit.com/r/Frugal/comments/cyhyjd/what_are_some_freecheap_activities_you_do_for_fun/eyvnv5x/) with the text "Calisthenics" that lacks any replies.
But in the corresponding HTML page generated by `reddit-html-archiver` the same comment has 5 out-of-context replies.

Is this a bug?

**Comment by libertysoft3** [comment]
Thanks a bunch man! It was a bug, apparently I didn't know how strip() works. If you regenerate your html it should look better.

> to update an html archive, delete everything in r aside from r/static and re-run write_html.py to regenerate everything.
