### ISSUE TITLE
Save local copies of images and gifs

### ISSUE THREAD

**Issue by growl360** [libertysoft3/reddit-html-archiver#17]
Thanks alot for making this @libertysoft3.

Images are the most important part of Reddit so I think saving local copies of images/gifs/videos would be a good idea (from encrypted-tbn0.gstatic.com, Imgur.com, tinypic.com, glyfcat.com, redditimages.com, vreddit.com etc.

**Comment by libertysoft3** [comment]
Yes this has been requested before, so it'd be good to add. Posts only or posts and comments?

**Comment by growl360** [comment]
I think it should be posts and comments as well. Very useful espically when you're on meme subs.

**Comment by saberman888** [comment]
If it helps the modifications I made to my fork add some image support, including Imgur support for single images. Theres also [ruanchaves' plugin](https://github.com/ruanchaves/reddit-html-archiver-image-plugin) you could use which also downloads the images

**Comment by growl360** [comment]
Looks pretty good Saberman 888

**Comment by libertysoft3** [comment]
Duplicate of #7
