### ISSUE TITLE
Unicode error prompts when trying to encode character

### ISSUE THREAD

**Issue by saberman888** [libertysoft3/reddit-html-archiver#2]
I've been getting this error when archiving subs such as r/Drama and r/RoleReversal. Is there anything I could do?
`Traceback (most recent call last):
  File "fetch_links.py", line 217, in <module>
    fetch_links(args.subreddit, args.date_start, args.date_stop, args.limit, args.score, self_only)
  File "fetch_links.py", line 81, in fetch_links
    success = write_links(subreddit, links)
  File "fetch_links.py", line 169, in write_links
    comments_writer.writerow(c)
  File "C:\Users\Sai\AppData\Local\Programs\Python\Python37-32\lib\csv.py", line 155, in writerow
    return self.writer.writerow(self._dict_to_list(rowdict))
  File "C:\Users\Sai\AppData\Local\Programs\Python\Python37-32\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\u0361' in position 10: character maps to <undefined>`

**Comment by libertysoft3** [comment]
Give this answer a shot, I've never tested this on Windows: https://stackoverflow.com/questions/32382686/unicodeencodeerror-charmap-codec-cant-encode-character-u2010-character-m

**Comment by libertysoft3** [comment]
I pushed an update which should resolve this. If it doesn't, check out the Windows section I added to the readme file. You can ignore my previous comment above.

**Comment by saberman888** [comment]
The stackoverflow thread didn't really work for me, but the updated you pushed really helped. thanks!
