### ISSUE TITLE
Add a license?

### ISSUE THREAD

**Issue by etnguyen03** [libertysoft3/reddit-html-archiver#24]
I have an idea for a project that would be based off this one. It'd be a major change that incorporates part of this project.

May I ask that a license be added to this project ([choosealicense.com](https://choosealicense.com/) has some options listed)?

I understand that it may be your intentions to not license this work, and if this is your intention, I will respect it.

Thank you!

**Comment by libertysoft3** [comment]
Cool I've never been asked to license anything! Does MIT sound okay?

**Comment by etnguyen03** [comment]
It'd be okay with me (any license is better than no license to me and anyone who may want to modify/improve on this project), but it's an issue that you need to consider along with anyone who may have contributed to this project. From a cursory review of the commit history, it seems like you are the only contributor, so the decision is yours.

If you attempt to create a file `LICENSE.md` in the root of the project using the Github online editor, Github will guide you (if you select "Choose a license template toward the right of the editor).
