### ISSUE TITLE
Case issues on Linux

### ISSUE THREAD

**Issue by emptythevoid** [libertysoft3/reddit-html-archiver#3]
On Linux, if you specify the subreddit all lower-case, it's possible for the write_html to get confused and end up with two directories - a  "r/subreddit" and a "r/Subreddit."  This makes comments and users break.  Instead of comments being /r/subreddit/comments, they become r/subreddit/r/Subreddit/comments.  Same for the users directory.

To prevent this, I call fetch_links with the first letter of the subreddit capitalized, but this might be handled better.

Example:  I was archiving r/piracy, so when I called fetch_links.py, I used ./fetch_links.py piracy 2011-1-1 2011-12-31  .  When I ran write_html.py, in r I ended up with directories piracy and Piracy.  The comments and user links inside the posts kept looking for the capitalized versions in r/piracy/r/Piracy, but that path didn't exist.  
This didn't happen when I called fetch_links like ./fetch_links.py **P**iracy 2011-1-1 2011-12-31

**Comment by libertysoft3** [comment]
I don't see how this scenario is possible unless you ran fetch_links.py with uppercase 'Piracy' once and lowercase 'piracy' once. write_html.py does not alter anything in 'data' and fetch_links.py uses the user provided capitalization throughout, unless I'm missing something.

With that being said, I put zero thought into capitalization. The sub should be displayed with the capitalization provided by the API and internally everything can be lowercase. So I should force the subreddit name from the command prompt to be lowercase it sounds like. Eh?

**Comment by emptythevoid** [comment]
Your fix worked!  Thank you!

Just so you know I'm not crazy, I got video of the behavior before your
fix.  https://www.youtube.com/watch?v=YsR9CgWj8rU
