### ISSUE TITLE
Fetch_links.py hangs indefinitely on writing data after 2020-09-01

### ISSUE THREAD

**Issue by 5000thinmints** [libertysoft3/reddit-html-archiver#30]
Reposting what I saw on reddit's r/pushshift since I'm having it as well on puppylinux, could never get this to run on win10.  I tried it last this summer on puppylinux, and didn't have hanging problems.

So if I run fetch_links on any sub I can think of and try to get data from 2020-09-01 onward it'll write a few comments and then hang, no more lines displayed and nothing being written to my folders, or catch another snag, 2020-09-15 is another date for me personally. I've reduced rate to 100 and tried to write 2020-09-01 2020-09-01 for a range with no luck. 

The author of the reddit post says it'll hang for days, most I've waited around is 6hrs or so, I'm assuming this is an indefinite hang. As with the author I'm not sure if its an issue with pushshift, or maybe some commands changed in order to fetch the data from pushshift and perhaps a few code changes are needed.

**Comment by libertysoft3** [comment]
From what I can tell, the script is working fine. There are potentially some holes in the data and potential issues on the pushshift side, I've heard of that before, but I need more info. There is also an exponential backoff if the requests are failing, which could look like a script hang. He should try running from a different ip addy with an unmodified script, or tell us what failed.

Working:

    python ./fetch_links.py redditalternatives 2020-9-1 2020-9-1
    python ./fetch_links.py redditalternatives 2020-9-1 2020-11-1
    python ./fetch_links.py conspiracy 2020-9-2 2020-9-2

Craps out with a pushshift 500 error:

    python ./fetch_links.py conspiracy 2020-9-1 2020-9-1

**Comment by libertysoft3** [comment]
I'm confident that this is a pushshift error, and psaw is not retrying after getting a 500 error. https://old.reddit.com/r/pushshift/comments/jxs3zw/having_difficulty_downloading_data_from_2020/
